version: '3.9'
services:
  app:
    image: gotodo
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - target=develop
    volumes:
      - .:/app
    ports:
      - 18000:80
