linters-settings:
  govet:
    check-shadowing: false
  gocyclo:
    min-complexity: 30
  misspell:
    locale: US
  
linters:
  disable-all: true
  enable:
    - deadcode
    - errcheck
    - gofmt
    - goimports
    - golint
    - gosimple
    - govet
    - ineffassign
    - interfacer
    - megacheck
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - gocyclo
    - goconst
    - depguard
    - dogsled
    - dupl
    - funlen
    - gochecknoinits
    - gochecknoglobals
    - gocognit
    - gosec
    - gocritic
    - nakedret
    - prealloc
    - scopelint
    - stylecheck
    - unconvert
    - interfacer
    - maligned
    - gofmt
    - goimports
    - govet
    - ineffassign
    - interfacer
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - gocyclo
    - goconst
    - depguard
    - dogsled
    - dupl
    - funlen
    - gochecknoinits
    - gochecknoglobals
    - gocognit
    - gosec
    - gocritic
    - nakedret
    - prealloc
    - scopelint
    - stylecheck
    - unconvert
    - interfacer
    - maligned
    - gofmt
    - goimports
    - govet
    - ineffassign
    - interfacer
    - misspell
    - staticcheck
    - structcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - varcheck
    - whitespace
    - gocyclo
    - goconst
    - depguard
    - dogsled
    - dupl
    - funlen
    - gochecknoinits
    - gochecknoglobals
    - gocognit
    - gosec